"""make_resume_ids_nullable

Revision ID: aee8ffda7711
Revises: 
Create Date: 2026-02-03 05:06:59.710115
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee8ffda7711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('resume_lang', sa.String(length=4), nullable=False),
    sa.Column('jd_lang', sa.String(length=4), nullable=False),
    sa.Column('desired_output_lang', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'complete', 'failed', name='job_status_enum'), server_default='queued', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("desired_output_lang in ('en','ar')", name='chk_desired_output_lang'),
    sa.CheckConstraint("jd_lang in ('en','ar')", name='chk_jd_lang'),
    sa.CheckConstraint("resume_lang in ('en','ar')", name='chk_resume_lang'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('upload', 'text', name='resume_source_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('task_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_type', sa.Enum('optimize', 'embed_resume', 'embed_job', name='task_type_enum'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'complete', 'failed', name='task_status_enum'), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_queue_created_at'), 'task_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_queue_status'), 'task_queue', ['status'], unique=False)
    op.create_table('workflow_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'indexed', 'failed', name='embedding_status_enum'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('optimizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('preview_md', sa.Text(), nullable=False),
    sa.Column('change_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimizations_created_at'), 'optimizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_optimizations_job_id'), 'optimizations', ['job_id'], unique=False)
    op.create_index(op.f('ix_optimizations_resume_id'), 'optimizations', ['resume_id'], unique=False)
    op.create_index(op.f('ix_optimizations_resume_version_id'), 'optimizations', ['resume_version_id'], unique=False)
    op.create_index(op.f('ix_optimizations_user_id'), 'optimizations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimizations_user_id'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_resume_version_id'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_resume_id'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_job_id'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_created_at'), table_name='optimizations')
    op.drop_table('optimizations')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_table('workflow_tokens')
    op.drop_index(op.f('ix_task_queue_status'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_created_at'), table_name='task_queue')
    op.drop_table('task_queue')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
